---
title: "Untitled"
author: "Autor: Manuel Spínola"
output:
  html_document:
    toc: true
    toc_depth: 6
    toc_float:
      collapsed: false
    code_download: true
---

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(rio)
library(collapse)
library(DescTools)
library(emmeans)
library(modelbased)
library(see)
library(parameters)
```


```{r}
ping <- import("03_datos/pinguinos.xlsx")
```


```{r}
ping$species <- factor(ping$species)
ping$sex <- factor(ping$sex)
```

```{r}
head(ping)
```

```{r}
ping <- na.omit(ping)
```


```{r}
adelie <- ping %>% filter(species == "Adelie")
```

```{r}
head(adelie)
```


```{r}
ggplot(adelie, aes(sex, body_mass_g)) +
  geom_boxplot() +
  geom_violin(alpha = 0.4) +
  geom_jitter(width = 0.2) +
  stat_summary(fun.data = "mean_cl_normal", colour = "red", size = 1)
```

```{r}
t.test(body_mass_g ~ sex, data = adelie, var.equal = TRUE)
```

alfa = 0.05
P < 0.05

```{r}
medias <- adelie %>%
  group_by(sex) %>%
  summarize(media = mean(body_mass_g))
```

```{r}
medias
```


```{r}
MeanDiffCI(body_mass_g ~ sex, data = adelie)
```
male - female = 675 (IC 95% = 573 , 776)

```{r}
mean(adelie$body_mass_g)
```


```{r}
675/3706
```

```{r}
mod <- lm(body_mass_g ~ sex, data = adelie)
```

```{r}
summary(mod)
```

```{r}
confint(mod)
```

```{r}
medias <- estimate_means(mod, "sex")
medias
```
```{r}
4043.49 - 3368.84 
```


```{r}
contraste <- estimate_contrasts(mod, "sex")
contraste
```

```{r}
e <- emmeans(mod, "sex")
```

```{r}
e
```

```{r}
p <- pairs(e)
```

```{r}
p
```
```{r}
confint(p)
```

```{r}
plot(p) + geom_vline(xintercept = 0)
```






